### PR TITLE
added provider

### PR DESCRIPTION
**Pull request by pratikagr**
provider is used for updating the text in homescreen.

### CODE REVIEW

**Comment by insfirred** [comment]
@pratikagr , resolve conflicts first

**Comment by pratikagr** [comment]
pls check

**Comment by insfirred** [comment]
Hey @pratikagr , The code in your Pull request is not changing the name in Home Screen since you resolve the conflicts. Can you check where is the problem

**Comment by pratikagr** [comment]
> Hey @pratikagr , The code in your Pull request is not changing the name in Home Screen since you resolve the conflicts. Can you check where is the problem

can you check once again

**Pull request closed without merging**
